const inquirer = require('inquirer')
const fsp = require ('fs/promises')
const questions =  require('./questions')
const { Circle, Square, Triangle } = require('./shapes')
const { SVGText, SVG } = require('./svg')
